title: Tasker
author: Tyler Pease
keywords: C#, school project
last_updated: November 7, 2022
markdown: kramdown

plugins: 
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - license
  - CNAME